apisix:
  node_listen:
    - port: 80
  enable_http2: true
  ssl:
    enable: true
    listen:
      - port: 443
        server_name: h-sandbox-apisix-api.cbi.id
    cert: /usr/local/apisix/conf/cert/fullchain.pem
    key: /usr/local/apisix/conf/cert/key.cbi.id.pem
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
  etcd:
    host:
      # - "http://localhost:2379"
      - "http://10.67.1.122:2379"
      - "http://10.67.2.181:2379"
      - "http://10.67.1.157:2379"
      - "http://10.67.2.102:2379"
  nginx_config:
    http:
      main_snippet: |
        client_body_buffer_size 256k;